const CAST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
// const DOCUMENT_NOT_FOUND_ERROR = 404;
// const CONFLICT_ERROR = 409;
const DEFAULT__SERVER_ERROR = 500;

module.exports = {
  CAST_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  DEFAULT__SERVER_ERROR,
};
